### ISSUE TITLE
How to fix wifi?

### ISSUE THREAD

**Issue by Alejandros29** [keystone-sideral/asus-ZC554KL#1]
I used the instructions from https://wiki.postmarketos.org/wiki/WiFi#Qualcomm_WiFi , but it does not work. it says echo: write error: Bad address - message. How to fix wifi?

**Comment by keystone-sideral** [comment]
hello with my kernel ?

**Comment by Alejandros29** [comment]
> hello with my kernel ?

yes.

**Comment by keystone-sideral** [comment]
Can you test:

sudo -i  
modprobe wlan  
echo modprobe wlan > /etc/local.d/wlan.start  
chmod +x /etc/local.d/wlan.start  
reboot  

Let me know if this fix wifi

**Comment by Alejandros29** [comment]
modprobe: can't load module wlan (kernel/drivers/staging/prima/wlan.ko): No such device
P.S. I use v22.06

**Comment by keystone-sideral** [comment]
Ok I have only tested in v21.12 can you test ? 
edit: use pmbootstrap zap -a before

**Comment by Alejandros29** [comment]
i watched dmesg log and see this.
[   10.753478] wcnss_wlan triggered by userspace
[   10.754064] wcnss_pm_qos_add_request: add request
[   10.754075] wcnss_pm_qos_update_request: update request 100
[   10.754370] wcnss_trigger_config: couldn't get snoc_wcnss
[   10.754393] wcnss_notif_cb: wcnss notification event: 2
[   10.754966] subsys-pil-tz a21b000.qcom,pronto: wcnss: loading from 0x000000008c900000 to 0x000000008cf44000
[   10.755008] wcnss_notif_cb: wcnss notification event: 6
[   10.758192] wcnss: IRIS Reg: 91100004
[   10.784407] scm_call failed: func id 0x42000201, ret: -2, syscall returns: 0xffffffffffffffff, 0x0, 0x0
[   10.786713] subsys-pil-tz a21b000.qcom,pronto: wcnss: Invalid firmware metadata
[   10.786763] wcnss_notif_cb: wcnss notification event: 7
[   10.793331] wcnss_notif_cb: wcnss notification event: 5
[   10.820850] PRONTO_PMU_SPARE 02000000
[   10.820855] PRONTO_PMU_COM_CPU_CBCR 80000ff0
[   10.820860] PRONTO_PMU_COM_AHB_CBCR 80000ff0
[   10.820864] PRONTO_PMU_CFG 00000010
[   10.820868] PRONTO_PMU_COM_CSR 00000000
[   10.820873] PRONTO_PMU_SOFT_RESET 00000400
[   10.820877] PRONTO_PMU_WDOG_CTL 80000ff0
[   10.820882] PRONTO_SAW2_SPM_STS 00003000
[   10.820887] PRONTO_SAW2_SPM_CTL 00000000
[   10.820892] PRONTO_SAW2_SAW2_VERSION 30000000
[   10.820896] PRONTO_PMU_CCPU_BOOT_REMAP 00000000
[   10.820901] PRONTO_PLL_STATUS 00000000
[   10.820905] PMU_CPU_CMD_RCGR 00000002
[   10.820910] PRONTO_PMU_COM_GDSCR 00222001
[   10.820911] Cannot log, Pronto common SS is power collapsed
[   10.880056] Cannot log, wlan domain is power collapsed
[   10.880062] wcnss_pm_qos_update_request: update request -1
[   10.880080] wcnss_pm_qos_remove_request: remove request
[   10.880097] wcnss_wlan a000000.qcom,wcnss-wlan: Peripheral Loader failed on WCNSS.
[   10.880099] wcnss_pm_qos_add_request: add request
[   10.880106] wcnss_pm_qos_update_request: update request 100
[   10.880119] PRONTO_PMU_SPARE 02000000
[   10.880124] PRONTO_PMU_COM_CPU_CBCR 80000ff0
[   10.880129] PRONTO_PMU_COM_AHB_CBCR 80000ff0
[   10.880133] PRONTO_PMU_CFG 00000010
[   10.880137] PRONTO_PMU_COM_CSR 00000000
[   10.880142] PRONTO_PMU_SOFT_RESET 00000400
[   10.880146] PRONTO_PMU_WDOG_CTL 80000ff0
[   10.880151] PRONTO_SAW2_SPM_STS 00003000
[   10.880156] PRONTO_SAW2_SPM_CTL 00000000
[   10.880161] PRONTO_SAW2_SAW2_VERSION 30000000
[   10.880166] PRONTO_PMU_CCPU_BOOT_REMAP 00000000
[   10.880170] PRONTO_PLL_STATUS 00000000
[   10.880174] PMU_CPU_CMD_RCGR 00000002
[   10.880178] PRONTO_PMU_COM_GDSCR 00222001
[   10.880180] Cannot log, Pronto common SS is power collapsed
[   10.940112] Cannot log, wlan domain is power collapsed
[   10.940144] wcnss_notif_cb: wcnss notification event: 2
[   10.940290] subsys-pil-tz a21b000.qcom,pronto: wcnss: loading from 0x000000008c900000 to 0x000000008cf44000
[   10.940350] wcnss_notif_cb: wcnss notification event: 6
[   10.944689] wcnss: IRIS Reg: 91100004
[   10.974089] scm_call failed: func id 0x42000201, ret: -2, syscall returns: 0xffffffffffffffff, 0x0, 0x0
[   10.976402] subsys-pil-tz a21b000.qcom,pronto: wcnss: Invalid firmware metadata
[   10.976461] wcnss_notif_cb: wcnss notification event: 7
[   10.982500] wcnss_notif_cb: wcnss notification event: 5
[   11.010812] PRONTO_PMU_SPARE 02000000
[   11.010817] PRONTO_PMU_COM_CPU_CBCR 80000ff0
[   11.010822] PRONTO_PMU_COM_AHB_CBCR 80000ff0
[   11.010826] PRONTO_PMU_CFG 00000010
[   11.010831] PRONTO_PMU_COM_CSR 00000000
[   11.010835] PRONTO_PMU_SOFT_RESET 00000400
[   11.010840] PRONTO_PMU_WDOG_CTL 80000ff0
[   11.010845] PRONTO_SAW2_SPM_STS 00003000
[   11.010849] PRONTO_SAW2_SPM_CTL 00000000
[   11.010854] PRONTO_SAW2_SAW2_VERSION 30000000
[   11.010859] PRONTO_PMU_CCPU_BOOT_REMAP 00000000
[   11.010863] PRONTO_PLL_STATUS 00000000
[   11.010868] PMU_CPU_CMD_RCGR 00000002
[   11.010872] PRONTO_PMU_COM_GDSCR 00222001
[   11.010874] Cannot log, Pronto common SS is power collapsed
[   11.070053] Cannot log, wlan domain is power collapsed
[   11.070064] wcnss_pm_qos_update_request: update request -1
[   11.070085] wcnss_pm_qos_remove_request: remove request
[   11.070103] wcnss_wlan a000000.qcom,wcnss-wlan: Peripheral Loader failed on WCNSS.
[   11.070108] wcnss_pm_qos_add_request: add request
[   11.070117] wcnss_pm_qos_update_request: update request 100
[   11.070133] PRONTO_PMU_SPARE 02000000
[   11.070139] PRONTO_PMU_COM_CPU_CBCR 80000ff0
[   11.070146] PRONTO_PMU_COM_AHB_CBCR 80000ff0
[   11.070153] PRONTO_PMU_CFG 00000010
[   11.070160] PRONTO_PMU_COM_CSR 00000000
[   11.070167] PRONTO_PMU_SOFT_RESET 00000400
[   11.070173] PRONTO_PMU_WDOG_CTL 80000ff0
[   11.070180] PRONTO_SAW2_SPM_STS 00003000
[   11.070187] PRONTO_SAW2_SPM_CTL 00000000
[   11.070194] PRONTO_SAW2_SAW2_VERSION 30000000
[   11.070201] PRONTO_PMU_CCPU_BOOT_REMAP 00000000
[   11.070208] PRONTO_PLL_STATUS 00000000
[   11.070214] PMU_CPU_CMD_RCGR 00000002
[   11.070221] PRONTO_PMU_COM_GDSCR 00222001
[   11.070225] Cannot log, Pronto common SS is power collapsed
[   11.130048] Cannot log, wlan domain is power collapsed
[   11.130076] wcnss_notif_cb: wcnss notification event: 2
[   11.130211] subsys-pil-tz a21b000.qcom,pronto: wcnss: loading from 0x000000008c900000 to 0x000000008cf44000
[   11.130272] wcnss_notif_cb: wcnss notification event: 6
[   11.134555] wcnss: IRIS Reg: 91100004
[   11.163959] scm_call failed: func id 0x42000201, ret: -2, syscall returns: 0xffffffffffffffff, 0x0, 0x0
[   11.166241] subsys-pil-tz a21b000.qcom,pronto: wcnss: Invalid firmware metadata
[   11.166300] wcnss_notif_cb: wcnss notification event: 7
[   11.172289] wcnss_notif_cb: wcnss notification event: 5
[   11.200773] PRONTO_PMU_SPARE 02000000
[   11.200782] PRONTO_PMU_COM_CPU_CBCR 80000ff0
[   11.200790] PRONTO_PMU_COM_AHB_CBCR 80000ff0
[   11.200796] PRONTO_PMU_CFG 00000010
[   11.200803] PRONTO_PMU_COM_CSR 00000000
[   11.200810] PRONTO_PMU_SOFT_RESET 00000400
[   11.200817] PRONTO_PMU_WDOG_CTL 80000ff0
[   11.200824] PRONTO_SAW2_SPM_STS 00003000
[   11.200831] PRONTO_SAW2_SPM_CTL 00000000
[   11.200838] PRONTO_SAW2_SAW2_VERSION 30000000
[   11.200845] PRONTO_PMU_CCPU_BOOT_REMAP 00000000
[   11.200852] PRONTO_PLL_STATUS 00000000
[   11.200859] PMU_CPU_CMD_RCGR 00000002
[   11.200865] PRONTO_PMU_COM_GDSCR 00222001
[   11.200869] Cannot log, Pronto common SS is power collapsed
[   11.260043] Cannot log, wlan domain is power collapsed
[   11.260050] wcnss_pm_qos_update_request: update request -1
[   11.260070] wcnss_pm_qos_remove_request: remove request
[   11.260087] wcnss_wlan a000000.qcom,wcnss-wlan: Peripheral Loader failed on WCNSS.
[   11.260091] wcnss_pm_qos_add_request: add request
[   11.260101] wcnss_pm_qos_update_request: update request 100
[   11.260116] PRONTO_PMU_SPARE 02000000
[   11.260123] PRONTO_PMU_COM_CPU_CBCR 80000ff0
[   11.260130] PRONTO_PMU_COM_AHB_CBCR 80000ff0
[   11.260136] PRONTO_PMU_CFG 00000010
[   11.260143] PRONTO_PMU_COM_CSR 00000000
[   11.260150] PRONTO_PMU_SOFT_RESET 00000400
[   11.260157] PRONTO_PMU_WDOG_CTL 80000ff0
[   11.260163] PRONTO_SAW2_SPM_STS 00003000
[   11.260170] PRONTO_SAW2_SPM_CTL 00000000
[   11.260177] PRONTO_SAW2_SAW2_VERSION 30000000
[   11.260184] PRONTO_PMU_CCPU_BOOT_REMAP 00000000
[   11.260191] PRONTO_PLL_STATUS 00000000
[   11.260197] PMU_CPU_CMD_RCGR 00000002
[   11.260204] PRONTO_PMU_COM_GDSCR 00222001
[   11.260208] Cannot log, Pronto common SS is power collapsed
[   11.320060] Cannot log, wlan domain is power collapsed
[   11.320069] PRONTO_PMU_SPARE 02000000
[   11.320073] PRONTO_PMU_COM_CPU_CBCR 80000ff0
[   11.320078] PRONTO_PMU_COM_AHB_CBCR 80000ff0
[   11.320082] PRONTO_PMU_CFG 00000010
[   11.320086] PRONTO_PMU_COM_CSR 00000000
[   11.320091] PRONTO_PMU_SOFT_RESET 00000400
[   11.320095] PRONTO_PMU_WDOG_CTL 80000ff0
[   11.320100] PRONTO_SAW2_SPM_STS 00003000
[   11.320105] PRONTO_SAW2_SPM_CTL 00000000
[   11.320110] PRONTO_SAW2_SAW2_VERSION 30000000
[   11.320114] PRONTO_PMU_CCPU_BOOT_REMAP 00000000
[   11.320118] PRONTO_PLL_STATUS 00000000
[   11.320123] PMU_CPU_CMD_RCGR 00000002
[   11.320127] PRONTO_PMU_COM_GDSCR 00222001
[   11.320129] Cannot log, Pronto common SS is power collapsed
[   11.320134] wcnss_log_iris_regs: IRIS Registers [address] : value
[   11.320301] [0x00000004] : 0x0000ffff
[   11.320440] [0x00000005] : 0x0000ffff
[   11.320579] [0x00000011] : 0x0000ffff
[   11.320718] [0x0000001e] : 0x0000ffff
[   11.320857] [0x00000040] : 0x0000ffff
[   11.320996] [0x00000048] : 0x0000ffff
[   11.321135] [0x00000049] : 0x0000ffff
[   11.321274] [0x0000004b] : 0x0000ffff
[   11.321413] [0x00000000] : 0x0000ffff
[   11.321551] [0x00000001] : 0x0000ffff
[   11.321690] [0x0000004d] : 0x0000ffff
[   11.340212] wcnss_pm_qos_update_request: update request -1
[   11.340234] wcnss_pm_qos_remove_request: remove request

**Comment by Alejandros29** [comment]
I figured out why my Wi-Fi is not working. Your version is 3/32. And I have version 2/16. These models have different processors and, accordingly, different drivers , but the fact that it booted up and works can be called a miracle.

**Comment by keystone-sideral** [comment]
Ok I understand.
Thank you for your feedback
I will clarify this on the readme.md
have a nice day.
